export const notes = {
  A0: {
    id: 'A0',
    name: 'Lá',
    cipher: 'A',
    src: 'https://storage.cloud.google.com/guitar-notes-storage/notes/guitar/A0.wav',
    frequency: [110, 109],
    correct: false,
  },
  A1: {
    id: 'A1',
    name: 'Lá#',
    cipher: 'A#',
    src: 'https://storage.cloud.google.com/guitar-notes-storage/notes/guitar/A1.wav',
    frequency: [116.5],
    correct: false,
  },
  A2: {
    id: 'A2',
    name: 'Si',
    cipher: 'B',
    src: 'https://storage.cloud.google.com/guitar-notes-storage/notes/guitar/A2.wav',
    frequency: [123.2],
    correct: false,
  },
  A3: {
    id: 'A3',
    name: 'Dó',
    cipher: 'C',
    src: 'https://storage.cloud.google.com/guitar-notes-storage/notes/guitar/A3.wav',
    frequency: [130.7],
    correct: false,
  },
  A4: {
    id: 'A4',
    name: 'Dó#',
    cipher: 'C#',
    src: 'https://storage.cloud.google.com/guitar-notes-storage/notes/guitar/A4.wav',
    frequency: [138.1],
    correct: false,
  },
  A5: {
    id: 'A5',
    name: 'Ré',
    cipher: 'D',
    src: 'https://storage.cloud.google.com/guitar-notes-storage/notes/guitar/A5.wav',
    frequency: [293.5],
    correct: false,
  },
  A6: {
    id: 'A6',
    name: 'Ré#',
    cipher: 'D#',
    src: 'https://storage.cloud.google.com/guitar-notes-storage/notes/guitar/A6.wav',
    frequency: [155],
    correct: false,
  },
  A7: {
    id: 'A7',
    name: 'Mi',
    cipher: 'E',
    src: 'https://storage.cloud.google.com/guitar-notes-storage/notes/guitar/A7.wav',
    frequency: [164.2],
    correct: false,
  },
  A8: {
    id: 'A8',
    name: 'Fá',
    cipher: 'F',
    src: 'https://storage.cloud.google.com/guitar-notes-storage/notes/guitar/A8.wav',
    frequency: [174.3],
    correct: false,
  },
  A9: {
    id: 'A9',
    name: 'Fá#',
    cipher: 'F#',
    src: 'https://storage.cloud.google.com/guitar-notes-storage/notes/guitar/A9.wav',
    frequency: [184.3],
    correct: false,
  },
  A10: {
    id: 'A10',
    name: 'Sol',
    cipher: 'G',
    src: 'https://storage.cloud.google.com/guitar-notes-storage/notes/guitar/A10.wav',
    frequency: [195.6],
    correct: false,
  },
  A11: {
    id: 'A11',
    name: 'Sol#',
    cipher: 'G#',
    src: 'https://storage.cloud.google.com/guitar-notes-storage/notes/guitar/A11.wav',
    frequency: [207.2],
    correct: false,
  },
  A12: {
    id: 'A12',
    name: 'Lá',
    cipher: 'A',
    src: 'https://storage.cloud.google.com/guitar-notes-storage/notes/guitar/A12.wav',
    frequency: [220.7],
    correct: false,
  },
  B0: {
    id: 'B0',
    name: 'Si',
    cipher: 'B',
    src: 'https://storage.cloud.google.com/guitar-notes-storage/notes/guitar/B0.wav',
    frequency: [246.5],
    correct: false,
  },
  B1: {
    id: 'B1',
    name: 'Dó',
    cipher: 'D',
    src: 'https://storage.cloud.google.com/guitar-notes-storage/notes/guitar/B1.wav',
    frequency: [262.9],
    correct: false,
  },
  B2: {
    id: 'B2',
    name: 'Dó#',
    cipher: 'D#',
    src: 'https://storage.cloud.google.com/guitar-notes-storage/notes/guitar/B2.wav',
    frequency: [277.5],
    correct: false,
  },
  B3: {
    id: 'B3',
    name: 'Ré',
    cipher: 'D',
    src: 'https://storage.cloud.google.com/guitar-notes-storage/notes/guitar/B3.wav',
    frequency: [294.1],
    correct: false,
  },
  B4: {
    id: 'B4',
    name: 'Ré#',
    cipher: 'D#',
    src: 'https://storage.cloud.google.com/guitar-notes-storage/notes/guitar/B4.wav',
    frequency: [311.6],
    correct: false,
  },
  B5: {
    id: 'B5',
    name: 'Mi',
    cipher: 'E',
    src: 'https://storage.cloud.google.com/guitar-notes-storage/notes/guitar/B5.wav',
    frequency: [330.6],
    correct: false,
  },
  B6: {
    id: 'B6',
    name: 'Fá',
    cipher: 'F',
    src: 'https://storage.cloud.google.com/guitar-notes-storage/notes/guitar/B6.wav',
    frequency: [349.5],
    correct: false,
  },
  B7: {
    id: 'B7',
    name: 'Fá#',
    cipher: 'F#',
    src: 'https://storage.cloud.google.com/guitar-notes-storage/notes/guitar/B7.wav',
    frequency: [370.5],
    correct: false,
  },
  B8: {
    id: 'B8',
    name: 'Sol',
    cipher: 'G',
    src: 'https://storage.cloud.google.com/guitar-notes-storage/notes/guitar/B8.wav',
    frequency: [394],
    correct: false,
  },
  B9: {
    id: 'B9',
    name: 'Sol#',
    cipher: 'G#',
    src: 'https://storage.cloud.google.com/guitar-notes-storage/notes/guitar/B9.wav',
    frequency: [416.8],
    correct: false,
  },
  B10: {
    id: 'B10',
    name: 'Lá',
    cipher: 'A',
    src: 'https://storage.cloud.google.com/guitar-notes-storage/notes/guitar/B10.wav',
    frequency: [440],
    correct: false,
  },
  B11: {
    id: 'B11',
    name: 'Lá#',
    cipher: 'A#',
    src: 'https://storage.cloud.google.com/guitar-notes-storage/notes/guitar/B11.wav',
    frequency: [467],
    correct: false,
  },
  B12: {
    id: 'B12',
    name: 'Si',
    cipher: 'B',
    src: 'https://storage.cloud.google.com/guitar-notes-storage/notes/guitar/B12.wav',
    frequency: [495.9],
    correct: false,
  },
  D0: {
    id: 'D0',
    name: 'Ré',
    cipher: 'D',
    src: 'https://storage.cloud.google.com/guitar-notes-storage/notes/guitar/D0.wav',
    frequency: [146.4],
    correct: false,
  },
  D1: {
    id: 'D1',
    name: 'Ré#',
    cipher: 'D#',
    src: 'https://storage.cloud.google.com/guitar-notes-storage/notes/guitar/D1.wav',
    frequency: [155.5],
    correct: false,
  },
  D2: {
    id: 'D2',
    name: 'Mi',
    cipher: 'E',
    src: 'https://storage.cloud.google.com/guitar-notes-storage/notes/guitar/D2.wav',
    frequency: [165],
    correct: false,
  },
  D3: {
    id: 'D3',
    name: 'Fá',
    cipher: 'F',
    src: 'https://storage.cloud.google.com/guitar-notes-storage/notes/guitar/D3.wav',
    frequency: [174.4],
    correct: false,
  },
  D4: {
    id: 'D4',
    name: 'Fá#',
    cipher: 'F#',
    src: 'https://storage.cloud.google.com/guitar-notes-storage/notes/guitar/D4.wav',
    frequency: [184.8],
    correct: false,
  },
  D5: {
    id: 'D5',
    name: 'Sol',
    cipher: 'G',
    src: 'https://storage.cloud.google.com/guitar-notes-storage/notes/guitar/D5.wav',
    frequency: [196],
    correct: false,
  },
  D6: {
    id: 'D6',
    name: 'Sol#',
    cipher: 'G#',
    src: 'https://storage.cloud.google.com/guitar-notes-storage/notes/guitar/D6.wav',
    frequency: [207.5],
    correct: false,
  },
  D7: {
    id: 'D7',
    name: 'Lá',
    cipher: 'A',
    src: 'https://storage.cloud.google.com/guitar-notes-storage/notes/guitar/D7.wav',
    frequency: [220],
    correct: false,
  },
  D8: {
    id: 'D8',
    name: 'Lá#',
    cipher: 'A#',
    src: 'https://storage.cloud.google.com/guitar-notes-storage/notes/guitar/D8.wav',
    frequency: [233.2],
    correct: false,
  },
  D9: {
    id: 'D9',
    name: 'Si',
    cipher: 'B',
    src: 'https://storage.cloud.google.com/guitar-notes-storage/notes/guitar/D9.wav',
    frequency: [246.8],
    correct: false,
  },
  D10: {
    id: 'D10',
    name: 'Dó',
    cipher: 'D',
    src: 'https://storage.cloud.google.com/guitar-notes-storage/notes/guitar/D10.wav',
    frequency: [262],
    correct: false,
  },
  D11: {
    id: 'D11',
    name: 'Dó#',
    cipher: 'D#',
    src: 'https://storage.cloud.google.com/guitar-notes-storage/notes/guitar/D11.wav',
    frequency: [277.2],
    correct: false,
  },
  D12: {
    id: 'D12',
    name: 'Ré',
    cipher: 'D',
    src: 'https://storage.cloud.google.com/guitar-notes-storage/notes/guitar/D12.wav',
    frequency: [294.7],
    correct: false,
  },
  E0: {
    id: 'E0',
    name: 'Mi',
    cipher: 'E',
    src: 'https://storage.cloud.google.com/guitar-notes-storage/notes/guitar/E0.wav',
    frequency: [82.5],
    correct: false,
  },
  E1: {
    id: 'E1',
    name: 'Fá',
    cipher: 'F',
    src: 'https://storage.cloud.google.com/guitar-notes-storage/notes/guitar/E1.wav',
    frequency: [87.5],
    correct: false,
  },
  E2: {
    id: 'E2',
    name: 'Fá#',
    cipher: 'F#',
    src: 'https://storage.cloud.google.com/guitar-notes-storage/notes/guitar/E2.wav',
    frequency: [92.5],
    correct: false,
  },
  E3: {
    id: 'E3',
    name: 'Sol',
    cipher: 'G',
    src: 'https://storage.cloud.google.com/guitar-notes-storage/notes/guitar/E3.wav',
    frequency: [97.6, 197],
    correct: false,
  },
  E4: {
    id: 'E4',
    name: 'Sol#',
    cipher: 'G#',
    src: 'https://storage.cloud.google.com/guitar-notes-storage/notes/guitar/E4.wav',
    frequency: [103],
    correct: false,
  },
  E5: {
    id: 'E5',
    name: 'Lá',
    cipher: 'A',
    src: 'https://storage.cloud.google.com/guitar-notes-storage/notes/guitar/E5.wav',
    frequency: [110],
    correct: false,
  },
  E6: {
    id: 'E6',
    name: 'Lá#',
    cipher: 'A#',
    src: 'https://storage.cloud.google.com/guitar-notes-storage/notes/guitar/E6.wav',
    frequency: [116],
    correct: false,
  },
  E7: {
    id: 'E7',
    name: 'Si',
    cipher: 'B',
    src: 'https://storage.cloud.google.com/guitar-notes-storage/notes/guitar/E7.wav',
    frequency: [123],
    correct: false,
  },
  E8: {
    id: 'E8',
    name: 'Dó',
    cipher: 'C',
    src: 'https://storage.cloud.google.com/guitar-notes-storage/notes/guitar/E8.wav',
    frequency: [130],
    correct: false,
  },
  E9: {
    id: 'E9',
    name: 'Dó#',
    cipher: 'C#',
    src: 'https://storage.cloud.google.com/guitar-notes-storage/notes/guitar/E9.wav',
    frequency: [138],
    correct: false,
  },
  E10: {
    id: 'E10',
    name: 'Ré',
    cipher: 'D',
    src: 'https://storage.cloud.google.com/guitar-notes-storage/notes/guitar/E10.wav',
    frequency: [146],
    correct: false,
  },
  E11: {
    id: 'E11',
    name: 'Ré#',
    cipher: 'D#',
    src: 'https://storage.cloud.google.com/guitar-notes-storage/notes/guitar/E11.wav',
    frequency: [155.3],
    correct: false,
  },
  E12: {
    id: 'E12',
    name: 'Mi',
    cipher: 'E',
    src: 'https://storage.cloud.google.com/guitar-notes-storage/notes/guitar/E12.wav',
    frequency: [165],
    correct: false,
  },
  e0: {
    id: 'ez0',
    name: 'Mi',
    cipher: 'E',
    src: 'https://storage.cloud.google.com/guitar-notes-storage/notes/guitar/ez0.wav',
    frequency: [330],
    correct: false,
  },
  e1: {
    id: 'ez1',
    name: 'Fá',
    cipher: 'F',
    src: 'https://storage.cloud.google.com/guitar-notes-storage/notes/guitar/ez1.wav',
    frequency: [349.3],
    correct: false,
  },
  e2: {
    id: 'ez2',
    name: 'Fá#',
    cipher: 'F#',
    src: 'https://storage.cloud.google.com/guitar-notes-storage/notes/guitar/ez2.wav',
    frequency: [370],
    correct: false,
  },
  e3: {
    id: 'ez3',
    name: 'Sol',
    cipher: 'G',
    src: 'https://storage.cloud.google.com/guitar-notes-storage/notes/guitar/ez3wav',
    frequency: [393.3],
    correct: false,
  },
  e4: {
    id: 'ez4',
    name: 'Sol#',
    cipher: 'G#',
    src: 'https://storage.cloud.google.com/guitar-notes-storage/notes/guitar/ez4.wav',
    frequency: [416.4],
    correct: false,
  },
  e5: {
    id: 'ez5',
    name: 'Lá',
    cipher: 'A',
    src: 'https://storage.cloud.google.com/guitar-notes-storage/notes/guitar/ez5.wav',
    frequency: [440],
    correct: false,
  },
  e6: {
    id: 'ez6',
    name: 'Lá#',
    cipher: 'A#',
    src: 'https://storage.cloud.google.com/guitar-notes-storage/notes/guitar/ez6.wav',
    frequency: [466.6],
    correct: false,
  },
  e7: {
    id: 'ez7',
    name: 'Si',
    cipher: 'B',
    src: 'https://storage.cloud.google.com/guitar-notes-storage/notes/guitar/ez7.wav',
    frequency: [494.4],
    correct: false,
  },
  e8: {
    id: 'ez8',
    name: 'Dó',
    cipher: 'C',
    src: 'https://storage.cloud.google.com/guitar-notes-storage/notes/guitar/ez8.wav',
    frequency: [523.2],
    correct: false,
  },
  e9: {
    id: 'ez9',
    name: 'Dó#',
    cipher: 'C#',
    src: 'https://storage.cloud.google.com/guitar-notes-storage/notes/guitar/ez9.wav',
    frequency: [553.8],
    correct: false,
  },
  e10: {
    id: 'ez10',
    name: 'Ré',
    cipher: 'D',
    src: 'https://storage.cloud.google.com/guitar-notes-storage/notes/guitar/ez10.wav',
    frequency: [583.8],
    correct: false,
  },
  e11: {
    id: 'ez11',
    name: 'Ré#',
    cipher: 'D#',
    src: 'https://storage.cloud.google.com/guitar-notes-storage/notes/guitar/ez11.wav',
    frequency: [620],
    correct: false,
  },
  e12: {
    id: 'ez12',
    name: 'Mi',
    cipher: 'E',
    src: 'https://storage.cloud.google.com/guitar-notes-storage/notes/guitar/ez12.wav',
    frequency: [661.2],
    correct: false,
  },
  G0: {
    id: 'G0',
    name: 'Sol',
    cipher: 'G',
    src: 'https://storage.cloud.google.com/guitar-notes-storage/notes/guitar/G0.wav',
    frequency: [195.7],
    correct: false,
  },
  G1: {
    id: 'G1',
    name: 'Sol#',
    cipher: 'G#',
    src: 'https://storage.cloud.google.com/guitar-notes-storage/notes/guitar/G1.wav',
    frequency: [208.4],
    correct: false,
  },
  G2: {
    id: 'G2',
    name: 'Lá',
    cipher: 'A',
    src: 'https://storage.cloud.google.com/guitar-notes-storage/notes/guitar/G2.wav',
    frequency: [220],
    correct: false,
  },
  G3: {
    id: 'G3',
    name: 'Lá#',
    cipher: 'A#',
    src: 'https://storage.cloud.google.com/guitar-notes-storage/notes/guitar/G3.wav',
    frequency: [233.4],
    correct: false,
  },
  G4: {
    id: 'G4',
    name: 'Si',
    cipher: 'B',
    src: 'https://storage.cloud.google.com/guitar-notes-storage/notes/guitar/G4.wav',
    frequency: [247.1],
    correct: false,
  },
  G5: {
    id: 'G5',
    name: 'Dó',
    cipher: 'C',
    src: 'https://storage.cloud.google.com/guitar-notes-storage/notes/guitar/G5.wav',
    frequency: [261.5],
    correct: false,
  },
  G6: {
    id: 'G6',
    name: 'Dó#',
    cipher: 'C#',
    src: 'https://storage.cloud.google.com/guitar-notes-storage/notes/guitar/G6.wav',
    frequency: [277],
    correct: false,
  },
  G7: {
    id: 'G7',
    name: 'Ré',
    cipher: 'D',
    src: 'https://storage.cloud.google.com/guitar-notes-storage/notes/guitar/G7.wav',
    frequency: [293.8],
    correct: false,
  },
  G8: {
    id: 'G8',
    name: 'Ré#',
    cipher: 'D#',
    src: 'https://storage.cloud.google.com/guitar-notes-storage/notes/guitar/G8.wav',
    frequency: [311.6],
    correct: false,
  },
  G9: {
    id: 'G9',
    name: 'Mi',
    cipher: 'E',
    src: 'https://storage.cloud.google.com/guitar-notes-storage/notes/guitar/G9.wav',
    frequency: [330],
    correct: false,
  },
  G10: {
    id: 'G10',
    name: 'Fá',
    cipher: 'F',
    src: 'https://storage.cloud.google.com/guitar-notes-storage/notes/guitar/G10.wav',
    frequency: [349.2],
    correct: false,
  },
  G11: {
    id: 'G11',
    name: 'Fá#',
    cipher: 'F#',
    src: 'https://storage.cloud.google.com/guitar-notes-storage/notes/guitar/G11.wav',
    frequency: [370],
    correct: false,
  },
  G12: {
    id: 'G12',
    name: 'Sol',
    cipher: 'G',
    src: 'https://storage.cloud.google.com/guitar-notes-storage/notes/guitar/G12.wav',
    frequency: [393.4],
    correct: false,
  },
};

export const allNote = [
  notes.E0,
  notes.E1,
  notes.E2,
  notes.E3,
  notes.E4,
  notes.E5,
  notes.E7,
  notes.E8,
  notes.E9,
  notes.E10,
  notes.E11,
  notes.E12,
  notes.A0,
  notes.A1,
  notes.A2,
  notes.A3,
  notes.A4,
  notes.A5,
  notes.A6,
  notes.A7,
  notes.A8,
  notes.A9,
  notes.A10,
  notes.A11,
  notes.A12,
  notes.D0,
  notes.D1,
  notes.D2,
  notes.D3,
  notes.D4,
  notes.D5,
  notes.D6,
  notes.D7,
  notes.D8,
  notes.D9,
  notes.D10,
  notes.D11,
  notes.G0,
  notes.G1,
  notes.G2,
  notes.G3,
  notes.G4,
  notes.G5,
  notes.G6,
  notes.G7,
  notes.G8,
  notes.G9,
  notes.G10,
  notes.G11,
  notes.G12,
  notes.B0,
  notes.B1,
  notes.B2,
  notes.B3,
  notes.B4,
  notes.B5,
  notes.B6,
  notes.B7,
  notes.B8,
  notes.B9,
  notes.B10,
  notes.B11,
  notes.B12,
  notes.e0,
  notes.e1,
  notes.e2,
  notes.e3,
  notes.e4,
  notes.e5,
  notes.e6,
  notes.e7,
  notes.e8,
  notes.e9,
  notes.e10,
  notes.e11,
  notes.e12,
];
