export const notes = {
  A0: {
    id: 'A0',
    name: 'Lá',
    cipher: 'A',
    src: 'notes/A0.wav',
  },
  A1: {
    id: 'A1',
    name: 'Lá#',
    cipher: 'A#',
    src: 'notes/A0.wav',
  },
  A2: {
    id: 'A2',
    name: 'Si',
    cipher: 'B',
    src: 'notes/A0.wav',
  },
  A3: {
    id: 'A3',
    name: 'Dó',
    cipher: 'C',
    src: 'notes/A0.wav',
  },
  A4: {
    id: 'A4',
    name: 'Dó#',
    cipher: 'C#',
    src: 'notes/A0.wav',
  },
  A5: {
    id: 'A5',
    name: 'Ré',
    cipher: 'D',
    src: 'notes/A0.wav',
  },
  A6: {
    id: 'A6',
    name: 'Ré#',
    cipher: 'D#',
    src: 'notes/A0.wav',
  },
  A7: {
    id: 'A7',
    name: 'Mi',
    cipher: 'E',
    src: 'notes/A0.wav',
  },
  A8: {
    id: 'A8',
    name: 'Fá',
    cipher: 'F',
    src: 'notes/A0.wav',
  },
  A9: {
    id: 'A9',
    name: 'Fá#',
    cipher: 'F#',
    src: 'notes/A0.wav',
  },
  A10: {
    id: 'A10',
    name: 'Sol',
    cipher: 'G',
    src: 'notes/A0.wav',
  },
  A11: {
    id: 'A11',
    name: 'Sol#',
    cipher: 'G#',
    src: 'notes/A0.wav',
  },
  A12: {
    id: 'A12',
    name: 'Lá',
    cipher: 'A',
    src: 'notes/A0.wav',
  },
  B0: {
    id: 'B0',
    name: 'Si',
    cipher: 'B',
    src: 'notes/B0.wav',
  },
  B1: {
    id: 'B1',
    name: 'Dó',
    cipher: 'D',
    src: 'notes/B1.wav',
  },
  B2: {
    id: 'B2',
    name: 'Dó#',
    cipher: 'D#',
    src: 'notes/B2.wav',
  },
  B3: {
    id: 'B3',
    name: 'Ré',
    cipher: 'D',
    src: 'notes/B3.wav',
  },
  B4: {
    id: 'B4',
    name: 'Ré#',
    cipher: 'D#',
    src: 'notes/B4.wav',
  },
  B5: {
    id: 'B5',
    name: 'Mi',
    cipher: 'E',
    src: 'notes/B5.wav',
  },
  B6: {
    id: 'B6',
    name: 'Fá',
    cipher: 'F',
    src: 'notes/B6.wav',
  },
  B7: {
    id: 'B7',
    name: 'Fá#',
    cipher: 'F#',
    src: 'notes/B7.wav',
  },
  B8: {
    id: 'B8',
    name: 'Sol',
    cipher: 'G',
    src: 'notes/B8.wav',
  },
  B9: {
    id: 'B9',
    name: 'Sol#',
    cipher: 'G#',
    src: 'notes/B9.wav',
  },
  B10: {
    id: 'B10',
    name: 'Lá',
    cipher: 'A',
    src: 'notes/B10.wav',
  },
  B11: {
    id: 'B11',
    name: 'Lá#',
    cipher: 'A#',
    src: 'notes/B11.wav',
  },
  B12: {
    id: 'B12',
    name: 'Si',
    cipher: 'B',
    src: 'notes/B12.wav',
  },
  D0: {
    id: 'D0',
    name: 'Ré',
    cipher: 'D',
    src: 'notes/D0.wav',
  },
  D1: {
    id: 'D1',
    name: 'Ré#',
    cipher: 'D#',
    src: 'notes/D1.wav',
  },
  D2: {
    id: 'D2',
    name: 'Mi',
    cipher: 'E',
    src: 'notes/D2.wav',
  },
  D3: {
    id: 'D3',
    name: 'Fá',
    cipher: 'F',
    src: 'notes/D3.wav',
  },
  D4: {
    id: 'D4',
    name: 'Fá#',
    cipher: 'F#',
    src: 'notes/D4.wav',
  },
  D5: {
    id: 'D5',
    name: 'Sol',
    cipher: 'G',
    src: 'notes/D5.wav',
  },
  D6: {
    id: 'D6',
    name: 'Sol#',
    cipher: 'G#',
    src: 'notes/D6.wav',
  },
  D7: {
    id: 'D7',
    name: 'Lá',
    cipher: 'A',
    src: 'notes/D7.wav',
  },
  D8: {
    id: 'D8',
    name: 'Lá#',
    cipher: 'A#',
    src: 'notes/D8.wav',
  },
  D9: {
    id: 'D9',
    name: 'Si',
    cipher: 'B',
    src: 'notes/D9.wav',
  },
  D10: {
    id: 'D10',
    name: 'Dó',
    cipher: 'D',
    src: 'notes/D10.wav',
  },
  D11: {
    id: 'D11',
    name: 'Dó#',
    cipher: 'D#',
    src: 'notes/D11.wav',
  },
  D12: {
    id: 'D12',
    name: 'Ré',
    cipher: 'D',
    src: 'notes/D12.wav',
  },
  E0: {
    id: 'E0',
    name: 'Mi',
    cipher: 'E',
    src: 'notes/E0.wav',
  },
  E1: {
    id: 'E1',
    name: 'Fá',
    cipher: 'F',
    src: 'notes/E1.wav',
  },
  E2: {
    id: 'E2',
    name: 'Fá#',
    cipher: 'F#',
    src: 'notes/E2.wav',
  },
  E3: {
    id: 'E3',
    name: 'Sol',
    cipher: 'G',
    src: 'notes/E3.wav',
  },
  E4: {
    id: 'E4',
    name: 'Sol#',
    cipher: 'G#',
    src: 'notes/E4.wav',
  },
  E5: {
    id: 'E5',
    name: 'Lá',
    cipher: 'A',
    src: 'notes/E5.wav',
  },
  E6: {
    id: 'E6',
    name: 'Lá#',
    cipher: 'A#',
    src: 'notes/E6.wav',
  },
  E7: {
    id: 'E7',
    name: 'Si',
    cipher: 'B',
    src: 'notes/E7.wav',
  },
  E8: {
    id: 'E8',
    name: 'Dó',
    cipher: 'C',
    src: 'notes/E8.wav',
  },
  E9: {
    id: 'E9',
    name: 'Dó#',
    cipher: 'C#',
    src: 'notes/E9.wav',
  },
  E10: {
    id: 'E10',
    name: 'Ré',
    cipher: 'D',
    src: 'notes/E10.wav',
  },
  E11: {
    id: 'E11',
    name: 'Ré#',
    cipher: 'D#',
    src: 'notes/E11.wav',
  },
  E12: {
    id: 'E12',
    name: 'Mi',
    cipher: 'E',
    src: 'notes/E12.wav',
  },
  e0: {
    id: 'ez0',
    name: 'Mi',
    cipher: 'E',
    src: 'notes/ez0.wav',
  },
  e1: {
    id: 'ez1',
    name: 'Fá',
    cipher: 'F',
    src: 'notes/ez1.wav',
  },
  e2: {
    id: 'ez2',
    name: 'Fá#',
    cipher: 'F#',
    src: 'notes/ez2.wav',
  },
  e3: {
    id: 'ez3',
    name: 'Sol',
    cipher: 'G',
    src: 'notes/ez3.wav',
  },
  e4: {
    id: 'ez4',
    name: 'Sol#',
    cipher: 'G#',
    src: 'notes/ez4.wav',
  },
  e5: {
    id: 'ez5',
    name: 'Lá',
    cipher: 'A',
    src: 'notes/ez5.wav',
  },
  e6: {
    id: 'ez6',
    name: 'Lá#',
    cipher: 'A#',
    src: 'notes/ez6.wav',
  },
  e7: {
    id: 'ez7',
    name: 'Si',
    cipher: 'B',
    src: 'notes/ez7.wav',
  },
  e8: {
    id: 'ez8',
    name: 'Dó',
    cipher: 'C',
    src: 'notes/ez8.wav',
  },
  e9: {
    id: 'ez9',
    name: 'Dó#',
    cipher: 'C#',
    src: 'notes/ez9.wav',
  },
  e10: {
    id: 'ez10',
    name: 'Ré',
    cipher: 'D',
    src: 'notes/ez10.wav',
  },
  e11: {
    id: 'ez11',
    name: 'Ré#',
    cipher: 'D#',
    src: 'notes/ez11.wav',
  },
  e12: {
    id: 'ez12',
    name: 'Mi',
    cipher: 'E',
    src: 'notes/ez12.wav',
  },
  G0: {
    id: 'G0',
    name: 'Sol',
    cipher: 'G',
    src: 'notes/G0.wav',
  },
  G1: {
    id: 'G1',
    name: 'Sol#',
    cipher: 'G#',
    src: 'notes/G1.wav',
  },
  G2: {
    id: 'G2',
    name: 'Lá',
    cipher: 'A',
    src: 'notes/G2.wav',
  },
  G3: {
    id: 'G3',
    name: 'Lá#',
    cipher: 'A#',
    src: 'notes/G3.wav',
  },
  G4: {
    id: 'G4',
    name: 'Si',
    cipher: 'B',
    src: 'notes/G4.wav',
  },
  G5: {
    id: 'G5',
    name: 'Dó',
    cipher: 'C',
    src: 'notes/G5.wav',
  },
  G6: {
    id: 'G6',
    name: 'Dó#',
    cipher: 'C#',
    src: 'notes/G6.wav',
  },
  G7: {
    id: 'G7',
    name: 'Ré',
    cipher: 'D',
    src: 'notes/G7.wav',
  },
  G8: {
    id: 'G8',
    name: 'Ré#',
    cipher: 'D#',
    src: 'notes/G8.wav',
  },
  G9: {
    id: 'G9',
    name: 'Mi',
    cipher: 'E',
    src: 'notes/G9.wav',
  },
  G10: {
    id: 'G10',
    name: 'Fá',
    cipher: 'F',
    src: 'notes/G10.wav',
  },
  G11: {
    id: 'G11',
    name: 'Fá#',
    cipher: 'F#',
    src: 'notes/G11.wav',
  },
  G12: {
    id: 'G12',
    name: 'Sol',
    cipher: 'G',
    src: 'notes/G12.wav',
  },
};

export const allNote = [
  notes.E0,
  notes.E1,
  notes.E2,
  notes.E3,
  notes.E4,
  notes.E5,
  notes.E7,
  notes.E8,
  notes.E9,
  notes.E10,
  notes.E11,
  notes.E12,
  notes.A0,
  notes.A1,
  notes.A2,
  notes.A3,
  notes.A4,
  notes.A5,
  notes.A6,
  notes.A7,
  notes.A8,
  notes.A9,
  notes.A10,
  notes.A11,
  notes.A12,
  notes.D0,
  notes.D1,
  notes.D2,
  notes.D3,
  notes.D4,
  notes.D5,
  notes.D6,
  notes.D7,
  notes.D8,
  notes.D9,
  notes.D10,
  notes.D11,
  notes.G0,
  notes.G1,
  notes.G2,
  notes.G3,
  notes.G4,
  notes.G5,
  notes.G6,
  notes.G7,
  notes.G8,
  notes.G9,
  notes.G10,
  notes.G11,
  notes.G12,
  notes.B0,
  notes.B1,
  notes.B2,
  notes.B3,
  notes.B4,
  notes.B5,
  notes.B6,
  notes.B7,
  notes.B8,
  notes.B9,
  notes.B10,
  notes.B11,
  notes.B12,
  notes.e0,
  notes.e1,
  notes.e2,
  notes.e3,
  notes.e4,
  notes.e5,
  notes.e6,
  notes.e7,
  notes.e8,
  notes.e9,
  notes.e10,
  notes.e11,
  notes.e12,
];
